name: Deploy Python Lambda

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: us-east-2
  LAMBDA_FUNCTION_NAME: alexa-conversation-skill
  PYTHON_VERSION: 3.13

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          mkdir -p package
          pip install -r requirements.txt -t ./package

      - name: Package Lambda
        run: |
          cp -r src/* package/
          cd package
          zip -r9 ../lambda.zip .
          cd ..

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip \
            --region ${{ env.AWS_REGION }}
