name: Deploy Python Lambda

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: us-east-2
  LAMBDA_FUNCTION_NAME: alexa-conversation-skill
  PYTHON_VERSION: 3.13

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          mkdir -p package
          pip install -r requirements.txt -t ./package

      - name: Package Lambda
        run: |
          cp -r src/* package/
          cd package
          zip -r9 ../lambda.zip .
          cd ..

      - name: Deploy Lambda with Environment Variables
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip

          aws lambda update-function-configuration \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --environment "Variables={
              \"DYNAMODB_TABLE_NAME\":\"${{ secrets.DYNAMODB_TABLE_NAME }}\",
              \"GROQ_API_KEY\":\"${{ secrets.GROQ_API_KEY }}\"
            }"

      - name: Verify Deployment
        run: |
          CONFIG=$(aws lambda get-function-configuration \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }})

          echo "$CONFIG" | jq '.Environment.Variables'

          if ! echo "$CONFIG" | jq -e '.Environment.Variables.DYNAMODB_TABLE_NAME' > /dev/null; then
            echo "¡Error: DYNAMODB_TABLE_NAME no está configurada!"
            exit 1
          fi

          if ! echo "$CONFIG" | jq -e '.Environment.Variables.GROQ_API_KEY' > /dev/null; then
            echo "¡Error: GROQ_API_KEY no está configurada!"
            exit 1
          fi
